# Generated by Django 4.0.3 on 2023-03-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.URLField()),
                ('host_status', models.BooleanField(default=False)),
                ('join_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking_rest.uservo')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('num_guests', models.IntegerField(default=1, null=True)),
                ('has_pets', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=255)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_rest.uservo')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_rest.rentalvo')),
            ],
        ),
    ]
