# Generated by Django 4.0.3 on 2023-03-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('photo', models.URLField()),
                ('host_status', models.BooleanField(default=False)),
                ('join_date', models.DateField()),
            ],
        ),
    ]
