# Generated by Django 4.0.3 on 2023-03-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0002_alter_user_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
