# Generated by Django 4.0.3 on 2023-03-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0003_alter_user_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
