# Generated by Django 4.0.3 on 2023-03-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0006_alter_user_password_rental_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!6OjJuNgNWtoy6AtX693Yc2Cu8XS1Y4A0W3OxOe1r', max_length=128),
        ),
    ]
