# Generated by Django 4.0.3 on 2023-03-15 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0007_remove_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superhost',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!wQq2cGdaD65Lsdsczx6ROjUJ79N0Z9ua1NxWN5Aj', max_length=128),
        ),
    ]
