# Generated by Django 4.0.3 on 2023-03-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0007_remove_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!ioviscDexRDWi9hbyfsfPRtG0fxrehrqKuaV7EiT', max_length=128),
        ),
    ]
