# Generated by Django 4.0.3 on 2023-03-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!loODjgmMxZ42xfWTIcJthMQZvRV5DqhHFaRbca8Y', max_length=128),
        ),
    ]
