# Generated by Django 4.0.3 on 2023-03-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0009_user_name_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!rdDy7z3ucbjvEvq6CfmaIGFLkYfInlD9Q0nIGNtF', max_length=128),
        ),
    ]
