# Generated by Django 4.0.3 on 2023-03-15 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0009_alter_user_password_rental_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='rental',
        ),
        migrations.AddField(
            model_name='rental',
            name='amenity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amenity', to='user_rest.amenity'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rental', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!OUbpWWCDDNHGGI6jWcvoiMFCW4JdNp1VtbOVsaOb', max_length=128),
        ),
    ]
