# Generated by Django 4.0.3 on 2023-03-15 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0010_remove_amenity_rental_rental_amenity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='amenity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='amenity', to='user_rest.amenity'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!JxXcsjOcJEof3tr5GLrX2pDAZx65Tt4GyZFtOb4I', max_length=128),
        ),
    ]
