# Generated by Django 4.0.3 on 2023-03-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_rest', '0012_alter_user_birthday_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='host_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superhost',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='!U5JXO1lCes03j3j6kE95ybaAEuOlpmfHzEfAjCwJ', max_length=128),
        ),
    ]
